#pragma config(Sensor, dgtl1,  Arm,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rtBack,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ltBack,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  MG,             sensorQuadEncoder)
#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port4,           ConeArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           MGLift,        tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port7,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           MGpusher,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Libraries/SmartMotorLib.c"
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
// line below prevents errors from unused functions in SmartMotor Library
#pragma systemFile

// finding the average between right and left Encoders in a task
int encAve;
task encAvgTask(){
	while(true){
		encAve = (SensorValue[rtBack] + SensorValue[ltBack]) / 2;
	}
}

// drive, setting motors in a function
void driveFunc(int rightPower, int leftPower){
	SetMotor (FR, rightPower);
	SetMotor (FL, leftPower);
	SetMotor (BR, rightPower);
	SetMotor (BL, leftPower);
}

void encDriving(int power, int encClicks){
	SensorValue[rtBack] = 0;
	SensorValue[ltBack] = 0;

	driveFunc(power,power);


	while(encAve < encClicks){

	}
	driveFunc(0,0);
}


// Setting MG Lift joystick buttons
// into task so that it will allow chassis to run at same time
int MGliftPower = 0;
task MGLiftTask(){
	while(true){
		// set up & down buttons
		MGliftPower = (vexRT[Btn6DXmtr2] - vexRT[Btn6UXmtr2]) * 90;
		SetMotor(MGLift, MGliftPower);

		// MG lift - move-to-bottom button
		if(vexRT[Btn8DXmtr2] == 1){
			if(SensorValue[MG] > 190){
				while(SensorValue[MG] > 600){
					SetMotor(MGLift, 90);
					wait1Msec(20);
				}
				SetMotor(MGLift, 0);
			}

			else{
				while(SensorValue[MG] < 250){
					SetMotor(MGLift, -50);
					wait1Msec(20);
				}
				SetMotor(MGLift, 0);



			}

		}
	}
}


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	SensorValue[Arm] = 0;
	SensorValue[MG] = 0;
	SensorValue[rtBack] = 0;
	SensorValue[ltBack] = 0;
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = false;
	SmartMotorsInit();
	SmartMotorsAddPowerExtender(ConeArm);
	SmartMotorLinkMotors(BR, FR);
	SmartMotorLinkMotors(BL, FL);
	SmartMotorCurrentMonitorEnable();

	SmartMotorRun();


	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	startTask(encAvgTask);

	//move backward to distance self from cone and stop
	driveFunc(-90, -90);
	wait1Msec(150);
	driveFunc(0, 0);
	wait1Msec(20);

	//pick up cone(arm down, and roll intake)
	clearTimer(T1);
	int killTimer = 2500;
	while ((SensorValue[Arm] > -264) && (time1[T1] < killTimer)){
		SetMotor(ConeArm, -90);
		wait1Msec(20);
	}
	SetMotor (ConeArm, 0);

	SetMotor (Roller, 127);
	wait1Msec(600);
	SetMotor (Roller, 20);


	//arm up (straight)
	while (SensorValue[Arm] < -190){
		SetMotor(ConeArm, 90);
		wait1Msec(20);
	}
	SetMotor(ConeArm, 0);

	// move MG to lowest level
	while (SensorValue[MG] < 250){
		SetMotor(MGLift, -50);
		wait1Msec(20);
	}
	SetMotor(MGLift, 0);
	wait1Msec(20);

	//drive backward to get mobile goal
	encDriving(-60,1550);

	//move MG picker upper up
	while (SensorValue[MG] < 800){
		SetMotor(MGLift, -90);
		wait1Msec(20);
	}
	SetMotor(MGLift,0);
	wait1Msec(20);

	// place cone on mobile goal
	clearTimer(T1);
	killTimer = 1500;
	while ((SensorValue[Arm] < -29) && (time1[T1] < killTimer)){
		SetMotor(ConeArm, 25);
		wait1Msec(20);

	}
	SetMotor(ConeArm, 0);
	SetMotor(Roller, 0);
	wait1Msec(20);

	// Turn after picking up mobile goal to face zone
	//180 degrees
	driveFunc(-80, 80);
	wait1Msec(1200);

	driveFunc(0, 0);
	wait1Msec(50);

	//hold MGLift up
	setMotor(MGLift, -60);
	wait1Msec(20);

	/*DRIVE FORWARD
	encDriving(-127,400); */

	//drive forward
	driveFunc(-80, -80);
	wait1Msec(725);

	driveFunc(0, 0);
	wait1Msec(50);

	//turn zigzag #1
	driveFunc(-80, 80);
	wait1Msec(750);

	driveFunc(0, 0);
	wait1Msec(50);

	//straight #2
	encDriving(-127,800);

	// MGLift, lift up higher
	SetMotor(MGLift, -90);

	//turn zig zag #2
	driveFunc(80, -80);
	wait1Msec(750);

	driveFunc(0, 0);
	wait1Msec(50);

	//drive to 20 point zone
	encDriving(-127,2000);

	setMotor(MGLift, 0);
	wait1Msec(50);

	//turn off MGLift
	setMotor(MGLift, 0);
	wait1Msec(50);

	//rolly outake lift up arm
	SetMotor(Roller, -127);
	wait1Msec(200);
	while (SensorValue[Arm] > -100){
		SetMotor(ConeArm, -127);
		wait1Msec(20);
	}
	SetMotor (ConeArm, 0);
	SetMotor (Roller, 0);
	wait1Msec(50);

	//MGpusher to push cone off MG
	SetMotor (MGpusher, 127);
	wait1Msec(1500);

	SetMotor (MGpusher, 0);

	// drive forward to ensure cone and MG go over
	driveFunc(-127, -127);
	wait1Msec(500);

	// drive away
	driveFunc(127, 127);
	wait1Msec(500);

	driveFunc(0, 0);

	//drive diagonally
	driveFunc(127,60);
	wait1Msec(2000);

	driveFunc(127,127);
	wait1Msec(2000);

	driveFunc(0,0);

	stopTask(encAvgTask);
}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	stopTask(autonomous);
	startTask(MGLiftTask);

	// User control code here, inside the loop

	// variables -------
	int rightpower = 0;
	int leftpower = 0;

	int ConeArmPower = 0;


#define MAX_POWER 127
#define DEADBAND 15

	while (true)
	{
		// Chassis
		leftpower = (vexRT[Ch3] + vexRT[Ch4]);
		rightpower = (vexRT[Ch3] - vexRT[Ch4]);

		if (abs(rightpower) > MAX_POWER){
			rightpower = sgn(rightpower) * MAX_POWER;
		}

		if (abs(leftpower) > MAX_POWER){
			leftpower = sgn(leftpower) * MAX_POWER;
		}

		if (abs(leftpower) < DEADBAND) leftpower = 0;
		if (abs(rightpower) < DEADBAND) rightpower = 0;


		// set left side motors;
		SetMotor(FL, leftpower);
		SetMotor(BL, leftpower);

		// set right side motors;
		SetMotor(FR, rightpower);
		SetMotor(BR, rightpower);

		//MGpusher
		if (vexRT[Btn5UXmtr2] == 1) {
			SetMotor(MGpusher, 127);
		}
		else if (vexRT[Btn5DXmtr2] == 1) {
			SetMotor(MGpusher, -127);
		}
		else SetMotor(MGpusher,0);



		// DISABLED ROLLER FOR DRIVER SKILLS
		// SINCE NOT PICKING UP CONES, and MG
		// CONTROL NOW ON PARTNER
		//Rolly Intake
		/*if(vexRT[Btn6UXmtr2] == 1){
		SetMotor(Roller, 80);
		}

		else if (vexRT[Btn6DXmtr2] == 1){
		SetMotor(Roller, -80);
		}
		else{
		SetMotor(Roller, 0);
		}*/


		// new roller button code
		// MGliftPower = (vexRT[Btn6UXmtr2] - vexRT[Btn6DXmtr2]) * 80;


		// Arm

		ConeArmPower = vexRT[Ch3Xmtr2];
		SetMotor(ConeArm,ConeArmPower);

	}
	stopTask(MGLiftTask);
}
