#pragma config(Sensor, dgtl1,  Arm,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rtBack,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ltBack,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  MG,             sensorQuadEncoder)
#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port4,           ConeArm,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Roller,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           MGLift,        tmotorVex393_MC29, openLoop, encoderPort, dgtl7)
#pragma config(Motor,  port7,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           MGpusher,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{

}





/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	while(true) {
		//CHASSIS
		if (vexRT[Btn6U] == 1) {
			motor[FR] = 50;
		}
		else{
			motor[FR] = 0;

		}
		if (vexRT[Btn6D] == 1) {
			motor[BR] = 50;
		}
		else{
			motor[BR] = 0;
		}

		if (vexRT[Btn5U] == 1) {
			motor[FL] = 50;
		}
		else{
			motor[FL] = 0;
		}

		if (vexRT[Btn5D] == 1) {
			motor[BL] = 50;
		}
		else{
			motor[BL] = 0;
		}

		//ARM
		motor[ConeArm]=vexRT[Ch3];

		//ROLLY INTAKE

		if (vexRT[Btn8U] == 1){
			motor[Roller] = 50;
		}
		else{
			motor[Roller] = 0;
		}

		//MG PUSHER

		if (vexRT[Btn7U] == 1) {
			motor [MGpusher] = 50;
		}
		else if (vexRT[Btn7D] == 1) {
			motor [MGpusher] = -50;
		}
		else motor [MGpusher] = 0;

		//MG LIFT

		if (vexRT[Btn7L] == 1) {
			motor [MGLift] = 50;
		}
		else if (vexRT[Btn7R] == 1) {
			motor [MGLift] = -50;
		}
		else motor [MGLift] = 0;

	}


}
