#pragma config(Sensor, in1,    bottomPOT,      sensorPotentiometer)
#pragma config(Sensor, in2,    topPOT,         sensorPotentiometer)
#pragma config(Sensor, dgtl2,  backRightENC,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  backLeftENC,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightBack,     tmotorServoContinuousRotation, openLoop, reversed, encoderPort, dgtl2)
#pragma config(Motor,  port3,           rightFront,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           bottomLift,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           topLift,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           claw,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           leftBack,      tmotorServoContinuousRotation, openLoop, encoderPort, dgtl4)
#pragma config(Motor,  port9,           leftFront,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download mthod as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

///SmartMotorLibrary by JPearman on the VEX forums
#include "Libraries/SmartMotorLib.c"

#pragma systemFile

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/



void waitUntilQuadrature(int sensorChosen, int amountToGo){
	int currentCount = SensorValue[sensorChosen];
	int finalAmount = currentCount + amountToGo;
	while(SensorValue[sensorChosen] <= finalAmount) {wait1Msec(10);}
}
void DriveStraight(int clicks, int power){
	SetMotor(rightBack, power, false);
	SetMotor (rightFront, power, false);
	SetMotor (leftBack, power, false);
	SetMotor (leftFront, power, false);

	waitUntilQuadrature(backLeftENC, clicks);
	SetMotor(rightBack, 0, false);
	SetMotor (rightFront, 0, false);
	SetMotor (leftBack, 0, false);
	SetMotor (leftFront, 0, false);
}

void changeClaw (int direction){
	if (direction == 1) { // 1 = open
		SetMotor (claw,80,false);
	}

	else {
		SetMotor (claw,-80,false);
	}
	wait1Msec(500);
	SetMotor(claw, 0, false);
}

void liftPOT (int power, int topPOTdest, int bottomPOTdest){
	int runloop=1;
	int topPOTvalue;
	int bottomPOTvalue;
	while (runloop==1){
		//potentiometer values
		topPOTvalue = SensorValue[topPOT];
		bottomPOTvalue = SensorValue[bottomPOT];
		if (topPOTvalue >= topPOTdest || bottomPOTvalue >= bottomPOTdest){
			{
				power = 0;
				power = 0;
				runloop=0;
				}
		}
		SetMotor(bottomLift, power, false);
			SetMotor(topLift, power, false);
}
		}

void lowerPOT (int power, int topPOTdest, int bottomPOTdest){
	int runloop=1;
	int topPOTvalue;
	int bottomPOTvalue;
	while (runloop==1){
		//potentiometer values
		topPOTvalue = SensorValue[topPOT];
		bottomPOTvalue = SensorValue[bottomPOT];
		if (topPOTvalue <= topPOTdest || bottomPOTvalue <= bottomPOTdest){
			{
				power = 0;
				power = 0;
				runloop=0;
				}
		}
		SetMotor(bottomLift, power, false);
			SetMotor(topLift, power, false);
}
		}


void pre_auton()
{

	SmartMotorsInit();
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	SmartMotorRun();
	SmartMotorPtcMonitorEnable ();

	//Drive forward
	wait1Msec(100);
  SetMotor(leftFront, 70, false);
  SetMotor(rightFront, 70, false);
  SetMotor(leftBack, 70, false);
  SetMotor(rightBack, 70, false);

  wait1Msec(500);

  SetMotor(leftFront, 0, false);
  SetMotor(rightFront, 0, false);
  SetMotor(leftBack, 0, false);
  SetMotor(rightBack, 0, false);

  wait1Msec(1000);

  // Drive Backwards
    SetMotor(leftFront, -70, false);
  SetMotor(rightFront, -70, false);
  SetMotor(leftBack, -70, false);
  SetMotor(rightBack, -70, false);

  wait1Msec(450);

  SetMotor(leftFront, 0, false);
  SetMotor(rightFront, 0, false);
  SetMotor(leftBack, 0, false);
  SetMotor(rightBack, 0, false);

  wait1Msec(1000);

	//Close Claw
	changeClaw (0);
  wait1Msec(500);
  SetMotor(claw,0,false);

	//Open Claw
	changeClaw (1);
  wait1Msec(500);
  SetMotor(claw,0,false);

	//Drive forwards
  SetMotor(leftFront, 70, false);
  SetMotor(rightFront, 70, false);
  SetMotor(leftBack, 70, false);
  SetMotor(rightBack, 70, false);

  wait1Msec(300);

  SetMotor(leftFront, 0, false);
  SetMotor(rightFront, 0, false);
  SetMotor(leftBack, 0, false);
  SetMotor(rightBack, 0, false);

  wait1Msec(1000);

	//Close Claw
	changeClaw(0);
	wait1Msec(1000);

	//Raise lift
	liftPOT (127, 1400, 1300);
	wait1Msec(1000);

	//Drive foward
	DriveStraight (230,100);
	wait1Msec(1000);

	//Lower lift
	lowerPOT(-90, 1000, 900);
	wait1Msec(100);

	//Open claw
	changeClaw (1);
	changeClaw (1);
	wait1Msec(100);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/


task usercontrol(){

	SmartMotorRun();
	SmartMotorPtcMonitorEnable();
	// chassis variables -------
	int rightpower = 0;
	int leftpower = 0;
	int adjLeft = 0;
	int adjRight = 0;
	int inverseBtn = 0;

	// claw variables -------
	int clawOpen = 0;
	int clawClose = 0;

	// lift variables --------
	int topPOTvalue;
	int bottomPOTvalue;
	int maxPOTtop = 2222;

	int maxPOTbottom = 2176;

	int topPower = 0;
	int bottomPower = 0;


#define MAX_POWER 127
#define DEADBAND 5

	while (true){
		////////// Chassis //////////
		leftpower = (vexRT[Ch3] + vexRT[Ch4]);
		rightpower = (vexRT[Ch3] - vexRT[Ch4]);

		if(abs(rightpower) > MAX_POWER){
			rightpower = sgn(rightpower) * MAX_POWER;
		}

		if(abs(leftpower) > MAX_POWER){
			leftpower = sgn(leftpower) * MAX_POWER;
		}

		if(abs(leftpower) < DEADBAND) leftpower = 0;
		if(abs(rightpower) < DEADBAND) rightpower = 0;

		// make the back of the robot the front
		// by pressing Button 6U
		inverseBtn = vexRT(Btn6U);
		if (inverseBtn == 1){
			leftpower = leftpower*-1;
			rightpower = rightpower*-1;
		}

		// set left side motors;
		SetMotor(leftFront, leftpower, false);
		SetMotor(leftBack, leftpower, false);

		// set right side motors;
		SetMotor(rightFront, rightpower, false);
		SetMotor(rightBack, rightpower, false);

		// small adjust
		adjLeft = vexRT[Btn7L];
		adjRight = vexRT[Btn7R];

		if (adjLeft == 1){
			SetMotor(rightFront, 70, false);
			SetMotor(rightBack, 70, false);
			SetMotor(leftFront, 0, false);
			SetMotor(leftBack, 0, false);
		}
		else if(adjRight == 1) {
			SetMotor(leftFront, 70, false);
			SetMotor(leftBack, 70, false);
			SetMotor(rightFront, 0, false);
			SetMotor(rightBack, 0, false);
		}
		////////// Claw //////////
		clawOpen = vexRT[Btn6UXmtr2];
		clawClose = vexRT[Btn6DXmtr2];

		if(clawClose == 1) SetMotor(claw, -100, false);
		else if( clawOpen == 1 ) SetMotor(claw, 100, false);
		else SetMotor(claw, 0, false);



		////////// Lift //////////

		//potentiometer values
		topPOTvalue = SensorValue[topPOT];
		bottomPOTvalue = SensorValue[bottomPOT];


		//LIFT
		topPower = vexRT[Ch3Xmtr2];
		bottomPower = vexRT[Ch3Xmtr2];

		if (topPOTvalue >= maxPOTtop || bottomPOTvalue >= maxPOTbottom){
			if (vexRT[Ch3Xmtr2] > 0 ){
				topPower = 0;
				bottomPower = 0;
			}
		}
		SetMotor(bottomLift, bottomPower, false);
			SetMotor(topLift, topPower, false);

		}
	}
